apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Values.global.namespace | default "voting-app" }}
  labels:
    app: result
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: result
