apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: {{ .Values.global.namespace | default "voting-app" }}
  labels:
    app: vote
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: vote
