apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Values.global.namespace | default "voting-app" }}
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "voting_app"
        - name: POSTGRES_USER
          value: "voting_user"
        - name: POSTGRES_PASSWORD
          value: "voting_password"
        resources:
          {{- toYaml .Values.postgresql.primary.resources | nindent 10 }}
        # Remove volume mounts entirely for now
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U voting_user -d voting_app
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U voting_user -d voting_app
          initialDelaySeconds: 5
          periodSeconds: 5
